spring:
  cloud:
    function:
      definition: uppercase|sentence

management:
  endpoints:
    web:
      exposure:
        include: functions,health
  endpoint:
    health:
      probes:
        enabled: true
